service: apiCachedClient
package:
  artifact: app/build/distributions/app.zip
  
provider:
  name: aws
  runtime: java17
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 6 # optional, in seconds, default is 6
  #versionFunctions: false
  environment:
    API_URL: ${env:API_URL}

functions:
  apiCachedClient:
    handler: kh.apiclient.ApiCachedClient