/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kh.apiclient;

import java.util.Map;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;

public class ApiCachedClient implements RequestHandler<Map<String,String>, String>{

	@Override
	public String handleRequest(Map<String, String> input, Context context) {
		// TODO Auto-generated method stub
		return null;
	}

}